services:
  mysql:
    container_name: barber-shop-mysql
    image: mysql:8.3.0
    restart: always
    environment:
      - MYSQL_TCP_PORT=3307
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=everydaydb
    ports:
      - "3307:3307"
    volumes:
      - db:/var/lib/mysql

  AdminMicroservice:
    image: "barber_app/admin_microservice"
    container_name: admin-ms
    build:
      context: /AdminMicroservice
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    restart: on-failure
    environment:
      MYSQL_URL: jdbc:mysql://localhost:3307
      SERVICE_PORT: 8081
    networks:
      - barber_app

  UserMicroservice:
    image: "barber_app/user_microservice"
    container_name: user-ms
    build:
      context: /UserApp
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 700m
    restart: on-failure
    environment:
      MYSQL_URL: jdbc:mysql://localhost:3307
      SERVICE_PORT: 8082
    networks:
      - barber_app

networks:
  barber_app:
    driver: "bridge"

volumes:
  db: